# fly.toml app configuration file generated for korean-laptop-lounge-bot on 2026-01-10T04:21:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'korean-laptop-lounge-bot'
primary_region = 'nrt'

[build]

[[mounts]]
  source = 'storage'
  destination = '/storage'

[http_service]
  internal_port = 3389
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '8gb'
  cpu_kind = 'performance'
  cpus = 4
  memory_mb = 8192
